### PR TITLE
Report manifest

### PR DESCRIPTION
**Pull request by brownag**
With this merge, report metadata will be specified in a mandatory `setup.R` file. All reports in soilReports have been updated to use this setup.R "report manifest" and verified to install correctly. See recent pull request #54 for commit that brought R11 reports into new system.

## **Changes:**

Below are the different elements that can be specified in setup.R:
```
.report.name
.report.version
.report.description
```
are all character strings. self explanatory.

```
.paths.to.copy
.update.paths.to.copy
``` 
are vectors of character strings pointing to files/directories to copy upon instantiating or updating a report. 
* `.paths.to.copy` is dealt with when initiating a report for the first time via `reportInit()`. 
* `.update.paths.to.copy` is used when calling `reportUpdate()`. reportUpdate is a wrapper for `reportInit(updateReport=TRUE)`. This resolves issue #3. 

The copyPath routine works recursively if paths to multi-tier folders are given. But overwrite must be set to true or must be in update mode to overwrite.

Optional arguments include:
```
.gh.packages.to.get 
.has.shiny.interface
```
which denote
 * set of packages ("username/repo@reference") to download from GitHub using `devtools::install_github()` 
* flag for whether the report has an interactive shiny.Rmd interface.

```
#soilReports test - pull request for report manifest

library(devtools)
install_github(repo="ncss-tech/soilReports@ReportManifest", dependencies=F, upgrade_dependencies=F)

library(soilReports)
foo <- listReports()
foo 

dir.create("report_tests")
setwd("report_tests")

update.reports=F
for(f in 1:nrow(foo)) {
  ff = foo[f,]
  reportSetup(ff$name)
  reportInit(reportName = ff$name,outputDir = ff$name,updateReport=update.reports)
}
```

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Wow, you have been busy. This is great stuff.

One minor request: can we still have access metadata variables within the report? Either as variables set at `reportInit` time or in the YAML header?

For example, it is nice to have the report version in the output HTML:
```r
report version `r .report.version`
```

Again, excellent work. Thank you!

**Comment by brownag** [comment]
## RE: metadata access from within report. 

Two options presented in commit 0bc4f65. These subroutine(s) would be used in reportInit() right before the HTML comment with the report name/version/creation date is prepended to the report.

### 1. YAML via `defineInYAMLHeader()`
```
<!-- mlra-comparison (v0.4) -- instance created 2017-07-05 11:38:55-->  
---
title: null
output:
  html_document:
    mathjax: null
    jquery: null
    smart: no
    keep_md: no
params:
	.report.name: a-report
	.report.version: 1.0
	.report.description: foo
---
```
### 2. R code chunk via `defineInCodeChunk()`
```
<!-- mlra-comparison (v0.4) -- instance created 2017-07-05 11:38:55-->  
---
title: null
output:
  html_document:
    mathjax: null
    jquery: null
    smart: no
    keep_md: no
---
```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
	.report.name <- "a-report"
	.report.version <- "1.0"
	.report.description <- "foo"
```
```

**Comment by dylanbeaudette** [comment]
Either way is fine with me, however, I kind of like the code chunk: seems less finnicky than the YAML. Also, the code chunk would play nicely with existing, local modifications to the YAML--region 11 reports for example.

**Comment by brownag** [comment]
7ceff3e

Realized that the HTML metadata comment is interfering with the parsing of YAML parameters! Need to append the comment AFTER the YAML header. 

I was worried about this when I first suggested the comment... but it didn't break with my (very simple) Rmds from region2... so I didn't think it would be a problem. My bad!

We have discussed that all reports should be able to (ideally) be run from a config file, interactively (e.g. KnitR+YAML or Shiny) and in batch. Report metadata are not true "parameters" and therefore the above solution regarding putting the metadata in the YAML header is not ideal. I also suspect it would complicate our efforts down the line. Though, `defineInYAMLHeader()` may prove itself useful, so I've left it in `reportInit.R`

We will be storing the instance copy of report metadata as an R code chunk. This will allow subversions of reports that end users may be modifying to be incremented and resulting outputs to update accordingly. Further, it will require very little to no change to existing code.

**Comment by brownag** [comment]
d60a956

Seems to work correctly. Placement of HTML comment shouldn't impede reports that rely on the correct parsing of YAML. 

The diffs for this commit are fairly small. That duplicated two-liner in listReports made the metadata not print correcltly. Not sure where that snuck in there. Also reversed order of comment/metadata block

**Comment by dylanbeaudette** [comment]
Thanks Andrew, I like the idea of keeping metadata / parameters split.

**Pull request merged**
